apiVersion: apps/v1
kind: Deployment
metadata:
  name: server0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server0
  template:
    metadata:
      labels:
        app: server0
    spec:
      containers:
        - name: server0
          image: SecureDataRegistry.azurecr.io/server0:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
