apiVersion: v1
kind: Service
metadata:
  name: server0-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: server0
---
apiVersion: v1
kind: Service
metadata:
  name: server1-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    app: server1
---
apiVersion: v1
kind: Service
metadata:
  name: server2-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  selector:
    app: server2
