apiVersion: v1
kind: Service
metadata:
  name: server0-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  selector:
    app: server0
  healthCheckNodePort: 32000
